{{- if .Values.grafana.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: wiki-grafana
  labels:
#    {{- include "wiki-chart.labels" . | nindent 4 }}
    app.kubernetes.io/component: wiki-grafana
spec:
  type: {{ .Values.grafana.service.type }}
  ports:
    - port: {{ .Values.grafana.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
#    {{- include "wiki-chart.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: wiki-grafana
{{- end }}