apiVersion: v1
kind: Service
metadata:
  name: wiki-fastapi
  labels:
#    {{- include "wiki-chart.labels" . | nindent 4 }}
    app.kubernetes.io/component: wiki-fastapi
spec:
  type: {{ .Values.fastapi.service.type }} #ClusterIP
  ports:
    - port: {{ .Values.fastapi.service.port }} # 8000
      targetPort: http
      protocol: TCP
      name: http
  selector:
#    {{- include "wiki-chart.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: wiki-fastapi
    